name: Run tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo xcode-select -s /Applications/Xcode_26.3.0.app
          swift test
