name: Tests

on: [push, workflow_dispatch]

jobs:
  swift:
    name: Swift
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.3.0.app

      - name: Run Swift test
        run: swift test
